In [2]:
import numpy as np

In [2]:
np.sqrt(25)

5.0

# Arrays

## np.array()

In [4]:
a = [0,1,2,3,4,5]
type(a)

list

In [5]:
type (np.array(a))

numpy.ndarray

## np.arange()

In [8]:
b = np.arange(4, 24, 2)
print (b)

[ 4  6  8 10 12 14 16 18 20 22]


## np.linspace()

In [12]:
c = np.linspace(1, 24, 3)
c

array([ 1. , 12.5, 24. ])

## np.zeros()

In [6]:
d = np.zeros(50)
d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## np.ones()

In [8]:
e = np.ones(50)
e

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Dimensiones

In [9]:
array_2d = np.array([d,e])

In [34]:
print(array_2d)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]]


## array.shape

In [21]:
array_2d.shape

(2, 50)

## array_size

In [23]:
array_2d.size

100

## array.ndim

In [25]:
array_2d.ndim

2

## Operaciones con arrays

In [27]:
lista_1 = [1, 2, 3] 
lista_2 = [4, 5, 6]

In [30]:
array_1 = np.array(lista_1)
array_2 = np.array(lista_2)

In [31]:
array_1 * array_2

array([ 4, 10, 18])

In [33]:
[num1 * num2 for num1, num2 in zip(lista_1, lista_2)]

[4, 10, 18]

# Funciones

## np.reshape()

In [38]:
array_2d.shape

(2, 50)

In [39]:
f = np.reshape(array_2d, (1,100))

In [40]:
f

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

## array.T

In [48]:
a = np.array([[1,2,3,4,5], [10, 20, 30, 40, 50]])
a

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [49]:
a.T

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40],
       [ 5, 50]])

## np.random

### np.random.randint

In [65]:
np.random.randint(0,300)


130

## np.where

In [66]:
array_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.]])

In [71]:
np.where(array_2d == 1, array_2d * 10, array_2d)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

# Estadistica

## Distribuciones

In [9]:
array_normal = np.random.normal(1.75, 0.05, 1000)

In [10]:
array_normal

array([1.70528223, 1.77516039, 1.74418702, 1.79143126, 1.76515081,
       1.7453358 , 1.71402811, 1.70373964, 1.82121716, 1.77004152,
       1.81598709, 1.7818226 , 1.79895827, 1.79563671, 1.75331819,
       1.73588875, 1.74575465, 1.7961637 , 1.80175001, 1.74656677,
       1.73862823, 1.79332257, 1.84829921, 1.7226101 , 1.73268196,
       1.73760114, 1.81815892, 1.73003684, 1.79579318, 1.67257458,
       1.70478413, 1.68158178, 1.80031091, 1.84899204, 1.8469945 ,
       1.7078061 , 1.84212339, 1.81537826, 1.74460841, 1.74138607,
       1.78731407, 1.73908451, 1.64880518, 1.67310585, 1.73521542,
       1.7690746 , 1.75214316, 1.63433399, 1.76225548, 1.6953267 ,
       1.79711739, 1.8049384 , 1.70981048, 1.77795566, 1.88763889,
       1.72307956, 1.76585784, 1.7703983 , 1.58979986, 1.72790784,
       1.75630352, 1.68300056, 1.76474339, 1.79951238, 1.69980163,
       1.70818745, 1.71131339, 1.70173108, 1.77713559, 1.74740935,
       1.76100996, 1.69040499, 1.71735819, 1.8356257 , 1.77940

## np.mean()

In [11]:
np.mean(array_normal)

1.750493599245819

## np.median()

In [12]:
np.median(array_normal)

1.7511942892025845

## nd.std()

In [13]:
np.std(array_normal)

0.04956458545315528